Repository ut-issl/s2e-aobc, pull requests merged in 2023-10, with the labels that each got.

#74 Add CubeWheel emulation.
  CMakeLists.txt
  data/initialize_files/components/cubewheelsmall.ini
  src/component/aocs/cube_wheel.cpp
  src/component/aocs/cube_wheel.h
Labels: :airplane: priority::medium, :dolphin: minor update

#70 Add doxygen comments
  src/component/aocs/aobc.cpp
  src/component/aocs/aobc.hpp
  src/component/aocs/mpu9250_gyro.cpp
  src/component/aocs/mpu9250_gyro.hpp
  src/component/aocs/mpu9250_mag.cpp
  src/component/aocs/mpu9250_mag.hpp
  src/component/aocs/mtq_seiren.cpp
  src/component/aocs/mtq_seiren.hpp
  src/component/aocs/nanossoc_d60.cpp
  src/component/aocs/nanossoc_d60.hpp
  src/component/aocs/oem7600.cpp
  src/component/aocs/oem7600.hpp
  src/component/aocs/rm3100.cpp
  src/component/aocs/rm3100.hpp
  src/component/aocs/rw0003.cpp
  src/component/aocs/rw0003.hpp
  src/component/aocs/sagitta.cpp
  src/component/aocs/sagitta.hpp
  src/component/aocs/stim210.cpp
  src/component/aocs/stim210.hpp
  src/component/power/ina260.cpp
  src/component/power/ina260.hpp
  src/component/power/power_controller.cpp
  src/component/power/power_controller.hpp
  src/interface/hils/hils_if_driver.cpp
  src/interface/hils/hils_if_driver.hpp
  src/library/crc.hpp
  src/simulation/case/sample_case.cpp
  src/simulation/case/sample_case.h
  src/simulation/spacecraft/aocs_module_components.cpp
  src/simulation/spacecraft/aocs_module_components.h
  src/simulation/spacecraft/aocs_module_port_config.h
  src/simulation/spacecraft/sample_satellite.cpp
  src/simulation/spacecraft/sample_satellite.h
Labels: :notebook: documentation, :airplane: priority::medium, :fish: patch

#77 Modify to suit with S2E-CORE Coding rule
  data/initialize_files/components/cube_wheel_small.ini
  data/initialize_files/satellite.ini
  src/component/aocs/aobc.cpp
  src/component/aocs/aobc.hpp
  src/component/aocs/cube_wheel.cpp
  src/component/aocs/cube_wheel.hpp
  src/component/aocs/mpu9250_gyro_sensor.cpp
  src/component/aocs/mpu9250_gyro_sensor.hpp
  src/component/aocs/mpu9250_magnetometer.cpp
  src/component/aocs/mpu9250_magnetometer.hpp
  src/component/aocs/mtq_seiren.cpp
  src/component/aocs/mtq_seiren.hpp
  src/component/aocs/nano_ssoc_d60.cpp
  src/component/aocs/nano_ssoc_d60.hpp
  src/component/aocs/oem7600.cpp
  src/component/aocs/oem7600.hpp
  src/component/aocs/rm3100.cpp
  src/component/aocs/rm3100.hpp
  src/component/aocs/rw0003.cpp
  src/component/aocs/rw0003.hpp
  src/component/aocs/sagitta.cpp
  src/component/aocs/sagitta.hpp
  src/component/aocs/stim210.cpp
  src/component/aocs/stim210.hpp
  src/component/power/ina260.cpp
  src/component/power/ina260.hpp
  src/component/power/power_controller.cpp
  src/component/power/power_controller.hpp
  src/interface/hils/hils_if_driver.cpp
  src/interface/hils/hils_if_driver.hpp
  src/library/crc.cpp
  src/library/crc.hpp
  src/s2e_aobc.cpp
  src/simulation/case/sample_case.cpp
  src/simulation/case/sample_case.hpp
  src/simulation/spacecraft/aocs_module_components.cpp
  src/simulation/spacecraft/aocs_module_components.hpp
  src/simulation/spacecraft/aocs_module_port_config.hpp
  src/simulation/spacecraft/sample_satellite.cpp
  src/simulation/spacecraft/sample_satellite.hpp
Labels: :notebook: documentation, :airplane: priority::medium, :whale: major update

#78 Remove warnings in Windows Visual Studio build
  src/component/aocs/oem7600.cpp
  src/component/aocs/oem7600.hpp
  src/component/aocs/rw0003.cpp
  src/component/aocs/stim210.cpp
  src/simulation/spacecraft/aocs_module_components.cpp
Labels: :airplane: priority::medium, :fish: patch

#80 Major version update v5.0.0
  .github/workflows/build.yml
  CMakeLists.txt
  README.md
  data/initialize_files/components/wings_command_sender_to_c2a/AOBC_CMD_DB_CMD_DB.csv
  data/initialize_files/components/wings_command_sender_to_c2a/ISSL6U_AOBC_CMD_DB_CMD_DB.csv
  data/initialize_files/components/wings_command_sender_to_c2a/wings_command_sender_to_c2a.ini
Labels: :airplane: priority::medium, :whale: major update

#83 [Hotfix] Fix c2a-aobc URL in readme
  CMakeLists.txt
  README.md
Labels: :notebook: documentation, :rocket: priority::high, :fish: patch

#84 Merge main to develop for Hotfix #83
  CMakeLists.txt
  README.md
Labels: :rocket: priority::high, :fish: patch

#85 SagittaのUnixTime変更コマンドに対応
  src/component/aocs/sagitta.cpp
  src/component/aocs/sagitta.hpp
Labels: :car: priority::low, :fish: patch
