Repository ut-issl/s2e-aobc, pull requests merged in 2024-05, with the labels that each got.

#92 Fix WGS key value name
  data/initialize_files/satellite.ini
Labels: :bug: bug, :rocket: priority::high, :fish: patch

#94 Update patch version v5.0.4
  CMakeLists.txt
Labels: :notebook: documentation, :rocket: priority::high, :fish: patch

#95 Fix bugs found in gain tuning test
  src/simulation/spacecraft/aocs_module_components.cpp
Labels: :bug: bug, :rocket: priority::high, :fish: patch

#96 rm3100固定センサバイアス値変更
  data/initialize_files/components/rm3100_aobc.ini
  data/initialize_files/components/rm3100_external.ini
Labels: :rocket: priority::high, :dolphin: minor update
